services:
  - type: web
    name: yonima-cargaison
    env: php
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATA_PATH
        value: /data
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /
    buildFilter:
      paths:
        - src/**/*.ts
        - public/**/*
        - package.json
        - tsconfig.json