services:
  - type: web
    name: yonima-cargaison
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DATA_PATH
        value: /data
    disk:
      name: data
      mountPath: /data
      sizeGB: 1